name: catchtable-clone

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: catchtable-db
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - catchtable-data:/var/lib/postgresql/data
      - ./data/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
      - ./data:/tmp/data
    networks:
      - catchtable-dev-net

  kafka:
    image: apache/kafka:3.7.0
    container_name: catchtable-kafka-dev
    user: "0"
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: "MkU3OEV5NURaZW52OTYyM2RjY1JqcA"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
    volumes:
      - kafka-data-dev:/tmp/kafka-logs
    networks:
      - catchtable-dev-net

networks:
  catchtable-dev-net:
    driver: bridge

volumes:
  catchtable-data:
  kafka-data-dev: