name: catchtable-clone

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: catchtable-db
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - catchtable-data:/var/lib/postgresql/data
      - ./data/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
      - ./data:/tmp/data

volumes:
  catchtable-data:
