spring:
  application:
    name: catchtable
  datasource:
    url: jdbc:postgresql://localhost:5432/catchtable
    username: teamE
    password: teamE
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
