springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

spring:
  application:
    name: catchtable
  datasource:
#    url: jdbc:postgresql://localhost:5433/catchtable
#    username: teamE
#    password: teamE
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/${DB_NAME:catchtable}
    username: ${DB_USER:teamE}
    password: ${DB_PASSWORD:teamE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
