receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  filter/drop_noise:
    error_mode: ignore
    traces:
      span:
        - 'attributes["http.target"] != nil and IsMatch(attributes["http.target"], "^/actuator.*")'
        - 'attributes["http.target"] != nil and IsMatch(attributes["http.target"], "^/favicon.*")'
        - 'attributes["http.status_code"] == 404 and attributes["http.target"] != nil and not IsMatch(attributes["http.target"], "^/(api|swagger-ui|api-docs).*")'

  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop_noise, batch]
      exporters: [otlp/jaeger]
  telemetry:
    logs:
      level: info
